### ISSUE TITLE
Some modules not found

### ISSUE THREAD

**Issue by scmartin** [davidhalter/jedi-vim#948]
### Issue

Trying to use jedi-vim with a python3 conda environment, I find that some modules are found but others are not, and result in "Omni completion (^O^N^P) Pattern not found. Some modules that are not working are
scipy
numpy
sympy
pandas

Examples of modules that are working
matplotlib
jsonschema
markupsafe

### Steps to reproduce

With the following minimal vim setup:
-   set nocompatible              " be iMproved, required
-   filetype off                  " required
-   let g:pymode_python = 'python3'
-   let &pythonthreedll = '/panfs/pfs.local/software/7/install/anaconda/4.7/lib/libpython3.7m.so.1.0'
-   color elflord
-   syntax on
-   filetype plugin on
-  set nu

Running ":python3 import numpy; print(np.arange(10))" returns the expected array.
" :python3 import sys; print(sys.path) " includes the path to my conda environment.

Not sure what else to try.

### Output of “:verbose JediDebugInfo”

 - jedi-vim git version: Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
 - jedi git submodule status: Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
 - parso git submodule status: Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `/home/sether35/.conda/envs/notebook/bin/python3`
 - global sys.version: `3.7.3 (default, Mar 27 2019, 22:15:47), [GCC 7.3.0]`
 - global site module: `/home/sether35/.conda/envs/notebook/lib/python3.7/site.py`

##### Jedi

 - path: `/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.15.1

##### Jedi environment: <SameEnvironment: 3.7.3 in /home/sether35/.conda/envs/notebook>

 - executable: /home/sether35/.conda/envs/notebook/bin/python3
 - sys_path:
    - `/panfs/pfs.local/work/laird/sether35/hoomd-blue`
    - `/panfs/pfs.local/home/sether35`
    - `/home/sether35/.conda/envs/notebook/lib/python37.zip`
    - `/home/sether35/.conda/envs/notebook/lib/python3.7`
    - `/home/sether35/.conda/envs/notebook/lib/python3.7/lib-dynload`
    - `/home/sether35/.conda/envs/notebook/lib/python3.7/site-packages`

##### Known environments

 - <Environment: 3.7.3 in /home/sether35/.conda/envs/notebook> (/home/sether35/.conda/envs/notebook/bin/python3.7)

 - <Environment: 2.7.5 in /usr> (/usr/bin/python2.7)

##### Settings

```
  omnifunc=jedi#completions
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim line 620
  completeopt=menuone,longest,preview
	Last set from ~/.vim/bundle/jedi-vim/plugin/jedi.vim line 36
```

#### :version
```

VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 18 2019 16:07:18)
Included patches: 1-2052
Compiled by r557e636@login1
Huge version without GUI.  Features included (+) or not (-):
+acl               +cindent           +cursorshape       +file_in_path      +jumplist          +mksession         +mouse_xterm       +printer           -sound             +terminal          +virtualedit       -xim
+arabic            +clientserver      +dialog_con        +find_in_path      +keymap            +modify_fname      +multi_byte        +profile           +spell             +terminfo          +visual            -xpm
+autocmd           +clipboard         +diff              +float             +lambda            +mouse             +multi_lang        +python/dyn        +startuptime       +termresponse      +visualextra       +xsmp_interact
+autochdir         +cmdline_compl     +digraphs          +folding           +langmap           -mouseshape        -mzscheme          +python3/dyn       +statusline        +textobjects       +viminfo           +xterm_clipboard
-autoservername    +cmdline_hist      -dnd               -footer            +libcall           +mouse_dec         +netbeans_intg     +quickfix          -sun_workshop      +textprop          +vreplace          -xterm_save
-balloon_eval      +cmdline_info      -ebcdic            +fork()            +linebreak         -mouse_gpm         +num64             +reltime           +syntax            +timers            +wildignore        
+balloon_eval_term +comments          +emacs_tags        +gettext           +lispindent        -mouse_jsbterm     +packages          +rightleft         +tag_binary        +title             +wildmenu          
-browse            +conceal           +eval              -hangul_input      +listcmds          +mouse_netterm     +path_extra        -ruby              -tag_old_static    -toolbar           +windows           
++builtin_terms    +cryptv            +ex_extra          +iconv             +localmap          +mouse_sgr         +perl              +scrollbind        -tag_any_white     +user_commands     +writebackup       
+byte_offset       +cscope            +extra_search      +insert_expand     +lua               -mouse_sysmouse    +persistent_undo   +signs             -tcl               +vartabs           +X11               
+channel           +cursorbind        -farsi             +job               +menu              +mouse_urxvt       +postscript        +smartindent       +termguicolors     +vertsplit         +xfontset          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/panfs/pfs.local/work/laird/sether35/sw/vim/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc -std=gnu99   -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm -ltinfo -lnsl    -ldl  -L/usr/lib -llua -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc        
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test.py" 14L, 183C
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 18 2019 16:07:18)
  1: ~/.vimrc
  2: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/ftoff.vim
  3: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/colors/elflord.vim
  4: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/syntax/syntax.vim
  5: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/syntax/synload.vim
  6: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/syntax/syncolor.vim
  7: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/filetype.vim
  8: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/ftplugin.vim
  9: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/getscriptPlugin.vim
 10: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/gzip.vim
 11: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/logiPat.vim
 12: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/manpager.vim
 13: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/matchparen.vim
 14: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/netrwPlugin.vim
 15: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/rrhelper.vim
 16: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/spellfile.vim
 17: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/tarPlugin.vim
```

<details><summary>:scriptnames</summary>

```
  1: ~/.vimrc
  2: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/ftoff.vim
  3: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/colors/elflord.vim
  4: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/syntax/syntax.vim
  5: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/syntax/synload.vim
  6: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/syntax/syncolor.vim
  7: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/filetype.vim
  8: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/ftplugin.vim
  9: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/getscriptPlugin.vim
 10: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/gzip.vim
 11: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/logiPat.vim
 12: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/manpager.vim
 13: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/matchparen.vim
 14: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/netrwPlugin.vim
 15: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/rrhelper.vim
 16: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/spellfile.vim
 17: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/tarPlugin.vim
 18: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/tohtml.vim
 19: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/vimballPlugin.vim
 20: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/plugin/zipPlugin.vim
 21: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 22: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 23: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 24: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 25: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 26: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 27: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 28: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 29: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 30: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 31: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 32: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 33: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 34: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 35: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 36: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 37: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 38: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 39: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 40: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 41: ~/.vim/bundle/nerdtree/nerdtree_plugin/vcs.vim
 42: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/syntax/python.vim
 43: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 44: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 45: ~/.vim/bundle/vim-flake8/ftplugin/python_flake8.vim
 46: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 47: /panfs/pfs.local/work/laird/sether35/sw/vim/share/vim/vim81/ftplugin/python.vim
 48: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
```
</details>

**Comment by davidhalter** [comment]
Does `python3 -c 'import numpy'` work?

And what is `:messages` after you complete numpy?

**Comment by scmartin** [comment]
python3 -c 'import numpy' does work.

:messages yields

"test.py" 14L, 183C
Traceback (most recent call last):
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset({('resolve_stars', True)}))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi_vim.py", line 262, in completions
    info=PythonToVimStr(c.docstring()),  # docstr
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 479, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 242, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 756, in docstring
    signature_text = _format_signatures(context)
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 715, in _format_signatures
    for signature in context.get_signatures()
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 715, in <genexpr>
    for signature in context.get_signatures()
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/evaluate/signature.py", line 28, in to_string
    s = self.name.string_name + '(' + ', '.join(param_strings()) + ')'
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/evaluate/signature.py", line 10, in param_strings
    for n in self.get_param_names(resolve_stars=True):
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/evaluate/signature.py", line 89, in get_param_names
    params = process_params(params)
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/evaluate/utils.py", line 20, in
wrapper
    return list(func(*args, **kwargs))
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/evaluate/star_args.py", line 135, in process_params
    for func_and_argument in arg_callables:
  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/evaluate/star_args.py", line 51, in _iter_nodes_for_param
    assert False
AssertionError

**Comment by blueyed** [comment]
>  File "/panfs/pfs.local/home/sether35/.vim/pack/plugins/start/jedi-vim/pythonx/jedi/jedi/evaluate/star_args.py", line 51, in _iter_nodes_for_param
>    assert False

Can you try updating the jedi submodule to master?  The code there changed, maybe it's fixed?

Anyway, this seems to be a Jedi issue (not jedi-vim).

**Comment by blueyed** [comment]
> Can you try updating the jedi and parso submodules to master? (in pythonx).

Not working, getting another error:
```
Traceback (most recent call last):
  File "…/vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 297, in completions
    info=PythonToVimStr(c.docstring()),  # docstr
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 477, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 240, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 754, in docstring
    signature_text = _format_signatures(value)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 713, in _format_signatures
    for signature in value.get_signatures()
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/klass.py", line 230, in get_signatures
    init_funcs = self.py__call__().py__getattribute__('__init__')
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 381, in py__getattribute__
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 381, in <genexpr>
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 88, in py__getattribute__
    names = self.goto(name_or_str, name_context, analysis_errors)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 77, in goto
    names = finder.filter_name(filters, name_or_str)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/finder.py", line 36, in filter_name
    for filter in filters:
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 63, in _get_value_filters
    for f in self.get_filters(origin_scope=origin_scope):
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/instance.py", line 154, in get_filters
    class_value = self.get_annotated_class_object()
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/instance.py", line 339, in get_annotated_class_object
    return self._get_annotated_class_object() or self.class_value
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/instance.py", line 323, in _get_annotated_class_object
    if not signature.matches_signature(args):
AttributeError: 'BuiltinSignature' object has no attribute 'matches_signature'
```

With:

```python
import numpy


numpy.
```

**Comment by scmartin** [comment]
I've notice that if I type a full function call (e.g. 'numpy.genfromtxt('  ), I get the function call signature to pop up as expected.

**Comment by blueyed** [comment]
That indicates that getting signatures works at least then..:)  (which is different code being used)

**Comment by GiBg1aN** [comment]
Hello, I got the same issue a few months ago and I downgraded the plugin to the last working version (at that moment **b9f83175951654256cff41737841b4abc0c9266d**). This workaround is still working for me. I hope this information might be useful for you.

**Comment by blueyed** [comment]
@GiBg1aN 
It might be more useful if you could git-bisect where this started to fail in jedi/parso submodules (assuming it is due to this), and/or provide a way to reproduce it easily.

**Comment by GiBg1aN** [comment]
I updated *jedi-vim* to the latest version, as expected it doesn't work for numpy, pandas, etc.

Then, with *jedi-vim* set to master, I downgraded *pythonx/jedi* to **davidhalter/jedi@6041503** which is the version used in the commit I referenced in the previous comment. It worked, so the issue is clearly with Jedi library. Here attached you can find the output of git-bisect on Jedi.

```
c490d37c2debc1dce2c8e275044a5ddf287cfd9b is the first bad commit
commit c490d37c2debc1dce2c8e275044a5ddf287cfd9b
Author: Dave Halter <davidhalter88@gmail.com>
Date:   Fri Jul 26 02:54:50 2019 +0200

    Start getting signature inferring working

 jedi/evaluate/names.py               |  29 +++++++++-
 jedi/evaluate/signature.py           | 109 +++++++++++++++++++++++++++++++++++
 test/test_evaluate/test_signature.py |  33 +++++++++++
 3 files changed, 169 insertions(+), 2 deletions(-)
```
and here is my minimal neovim config:
```
syntax on
filetype plugin on
set nocompatible
 
call plug#begin('~/.local/share/nvim/plugged')
Plug    'davidhalter/jedi-vim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:python3_host_prog = '/home/gibg1an/.conda/envs/torch/bin/python'
```

Let me know if you need other data.

**Comment by davidhalter** [comment]
If you want to help getting this fixed, please use direct Jedi calls and try to reproduce it that way. I'm still not at all sure what fails for you guys.

**Comment by GiBg1aN** [comment]
It's the first time that I try the API, I apologise in advance for (possible) silly errors.
I am currently working in the system environment (I removed anaconda reference from neovim config) in which I just installed numpy with pip. As before, if I type
```
import numpy

numpy.
```
the completion is not performed and the first error message reported in this issue is returned. 
As you requested I tried to reproduce the same behaviour from the code. I'm working with Jedi and Parso version contained inside the latest *jedi-vim* commit. I wrote the following script:
```
import jedi
source = '''
import numpy
numpy.'''

script = jedi.Script(source, 3, len('numpy.'), '')
completions = script.completions()
out = [x.complete for x in completions]
print(out)
```
and the `out` list is correctly non-empty. This means that the problem is not Jedi itself as I previously assumed. Do you have any experiments to propose?

**Comment by blueyed** [comment]
@GiBg1aN 
Check if the script also work from inside of Vim/Neovim, using `:!python …`.
And also check it with the Python (environment) version reported by `:JediDebugInfo`.

**Comment by GiBg1aN** [comment]
I'm not using environments at the moment, so both from neovim and the script is system python. I tried to run the script from neovim as you suggested and it works also in this case. Here attached you can find my `:JediDebugInfo` output.

```
 JediDebugInfo
#### Jedi-vim debug information


##### jedi-vim version


 - jedi-vim git version: 5880f2d-dirty
 - jedi git submodule status:  005f69390c4b1a3b864e7373cfcbdaf95e65411d pythonx/jedi (v0.15.1)
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: 5880f2d-dirty
 - jedi git submodule status:  005f69390c4b1a3b864e7373cfcbdaf95e65411d pythonx/jedi (v0.15.1)
 - parso git submodule status:  c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso (v0.5.1)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `/usr/bin/python3`
 - global sys.version: `3.7.4 (default, Oct  4 2019, 06:57:26), [GCC 9.2.0]`
 - global site module: `/usr/lib/python3.7/site.py`

##### Jedi

 - path: `/home/gibg1an/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.15.1

##### Jedi environment: <SameEnvironment: 3.7.4 in /usr>

 - executable: /usr/bin/python3
 - sys_path:
    - `/usr/lib/python37.zip`
    - `/usr/lib/python3.7`
    - `/usr/lib/python3.7/lib-dynload`
    - `/home/gibg1an/.local/lib/python3.7/site-packages`
    - `/usr/lib/python3.7/site-packages`

##### Known environments

 - <Environment: 3.7.4 in /usr> (/usr/bin/python3.7)
 - <Environment: 2.7.16 in /usr> (/usr/bin/python2.7)

##### Settings

  omnifunc=jedi#completions
        Last set from ~/.local/share/nvim/plugged/jedi-vim/autoload/jedi.vim line 740
  completeopt=menuone,longest,preview
        Last set from ~/.local/share/nvim/plugged/jedi-vim/plugin/jedi.vim line 36

```

**Comment by GiBg1aN** [comment]
I tried to disable docstrings on completion directly from the code, now the completion from jedi-vim works correctly. I'll try to check the code later. Anyway, at the moment I hypothesize that libraries like numpy, pandas, etc have a help docstring which fill the buffer/cache reserved for them, or something like that. Thus, the function call fails.

**Comment by blueyed** [comment]
@GiBg1aN 
Interesting.  Thanks for investigating already, and please follow up.
More information about what methods are affected etc would be useful, of course.

**Comment by GiBg1aN** [comment]
Probably the memory hypothesis is (at least partially) wrong. I noticed that if I keep typing the function i.e.
`numpy.a`
the completion list correctly appears, whereas if I start with
`numpy.b`
it fails (trying to debug a little, I discovered that it happens during the analysing of *numpy.broadcast* function) the same thing for `numpy.c` and many others.

So, something unexpected happens during signature extraction for the docstring for some functions in numpy.

In fact, if I set https://github.com/davidhalter/jedi-vim/blob/5880f2de93221bb6b8ade33bcd888047c86e8f05/pythonx/jedi_vim.py#L314
*info* parameter with an arbitrary string, it is displayed as docstring and the completion works.

I'm sorry, I don't know the codebase and the algorithm to perform a proper debug. Let me know if I can help you more.

**Comment by blueyed** [comment]
So `<c-x><c-o>` on `numpy.b` fails for you?  It works for me, and contains `broadcast`.
But it fails with parso v0.5.1 (the currently used version in the submodule), bisected to https://github.com/davidhalter/parso/commit/8f83e9b3c5c477d732b02b3adc9856264697bc33 (new, there it works).
For reference, I've used this to test it: `nvim -u minimal.vimrc t-numpy.py +'call feedkeys("GA\<c-x>\<c-o>")'`, with `minimal.vimrc`:
```vim
let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath = script_dir.','.&rtp.','.script_dir.'/after'
```
and `t-numpy.py`:
```python
import numpy


numpy.b
```
However, completion after just `numpy.` fails ("-- Omni completion (^O^N^P) Pattern not found").
`:mess` shows:
```python
Traceback (most recent call last):
  File "…/vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 314, in completions
    info=PythonToVimStr(c.docstring()),  # docstr
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 477, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 240, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 754, in docstring
    signature_text = _format_signatures(value)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 713, in _format_signatures
    for signature in value.get_signatures()
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/klass.py", line 230, in get_signatures
    init_funcs = self.py__call__().py__getattribute__('__init__')
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 381, in py__getattribute__
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 381, in <genexpr>
    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 88, in py__getattribute__
    names = self.goto(name_or_str, name_context, analysis_errors)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 77, in goto
    names = finder.filter_name(filters, name_or_str)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/finder.py", line 36, in filter_name
    for filter in filters:
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/base_value.py", line 63, in _get_value_filters
    for f in self.get_filters(origin_scope=origin_scope):
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/instance.py", line 154, in get_filters
    class_value = self.get_annotated_class_object()
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/instance.py", line 339, in get_annotated_class_object
    return self._get_annotated_class_object() or self.class_value
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/value/instance.py", line 323, in _get_annotated_class_object
    if not signature.matches_signature(args):
AttributeError: 'BuiltinSignature' object has no attribute 'matches_signature'
```
Jedi and Parso master.

**Comment by blueyed** [comment]
Created https://github.com/davidhalter/jedi/issues/1426.

**Comment by blueyed** [comment]
Please try https://github.com/davidhalter/jedi-vim/pull/958.

**Comment by blueyed** [comment]
Also @scmartin, please.

**Comment by GiBg1aN** [comment]
Good job! It works also with my full neovim setup.

**Comment by davidhalter** [comment]
@GiBg1aN I'd still be interested to understand the original issue. 

> It's the first time that I try the API, I apologise in advance for (possible) silly errors.

No worries, thanks for trying :)

> and the out list is correctly non-empty. 

You could try to use in the beginning:

```
import jedi
jedi.set_debug_function()
```

And post it here.

**Comment by davidhalter** [comment]
I'm reopening this, because the Jedi bug is not yet fixed. If you want @GiBg1aN you can also open an issue in the Jedi tracker. I'm fine with discussing this here though as well.

**Comment by GiBg1aN** [comment]
> You could try to use in the beginning:
> 
> ```
> import jedi
> jedi.set_debug_function()
> ```
> 
> And post it here.

[jedi_debug_log.txt](https://github.com/davidhalter/jedi-vim/files/3749555/jedi_debug_log.txt)

Here it is.

**Comment by davidhalter** [comment]
This was fixed in Jedi and since #974 is merged, it should all be fine again in jedi-vim as well.
