### ISSUE TITLE
Cannot autocomplete members of variables initialized with 'await'

### ISSUE THREAD

**Issue by tarcisioe** [davidhalter/jedi-vim#728]
### Issue

Members of variables initialized with `await ...` cannot be autocompleted.

### Steps to reproduce

Minimal example should be something like

```
async def f() -> str:
    return 'test'

async def main():
    # a = f()  # works, but is wrong. jedi autocompletes as if f() was not async, though.
    a = await f()
    a.
```

No completion happens after `a.`. In fact, after completion fails, erasing `await` does NOT make it work again.

#### Jedi-vim debug information
Using Python version: 3
 - sys.version: `3.6.1 (default, Apr 27 2017, 12:16:19), [GCC 5.4.0]`
 - site module: `/usr/lib64/python3.6/site.py`
Jedi path: `/home/tarcisioe/.configmanager/files/vim/plugged/jedi-vim/jedi/jedi/__init__.py`
 - version: 0.10.2
 - sys_path:
    - `/home/tarcisioe/.configmanager/files/vim/plugged/jedi-vim`
    - `/usr/lib64/python36.zip`
    - `/usr/lib64/python3.6`
    - `/usr/lib64/python3.6/lib-dynload`
    - `/home/tarcisioe/.local/lib64/python3.6/site-packages`
    - `/usr/lib64/python3.6/site-packages`
    - `_vim_path_`
 - jedi-vim git version: a2cf229
 - jedi git submodule status:  5427b02712828b2875d35b5ee1c8b5e58f820537 jedi (v0.10.2)

##### Settings
```
g:jedi#force_py_version = 3 (default: 'auto')
g:jedi#auto_vim_configuration = 0 (default: 1)


  omnifunc=jedi#completions
	Last set from ~/.configmanager/files/vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
  completeopt=menu
	Last set from ~/.configmanager/files/vim/init.vim
```

#### :version
```

NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -fomit-frame-pointer -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/config -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/include
Compiled by portage@jinx

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

#### :messages
```
W391: blank line at end of file

E999: SyntaxError: invalid syntax
E999: SyntaxError: invalid syntax
```

**Comment by davidhalter** [comment]
async/await support in Jedi is really bad. It just doesn't crash, but there's definitely no support for it.

**Comment by tarcisioe** [comment]
I see. Would you think it's too hard to implement at least a basic support for following the return types? I may be able to spend some time at it and attempt a PR.

**Comment by davidhalter** [comment]
That's probably pretty easy.

**Comment by NoAnyLove** [comment]
This jedi issue also breaks the functionality of showing function documentation after `await` statement.

A simple example to reproduce the issue,

```python
import asyncio

async def demo():
    while True:
        await asyncio.sleep(100)
```

Move your cursor on the `sleep` function, and press `K`. It will through the following exceptions,

```python
Exception, this shouldn't happen.
Traceback (most recent call last):
  File "C:\Users\NoAnyLove\AppData\Local\nvim\plugged\jedi-vim\pythonx\jedi_vim.py", line 311, in show_documentation
    definitions = script.goto_definitions()
  File "C:\Users\NoAnyLove\AppData\Local\nvim\plugged\jedi-vim\pythonx\jedi\jedi\api\__init__.py", line 204, in goto_definitions
    definitions = helpers.evaluate_goto_definition(self._evaluator, context, leaf)
  File "C:\Users\NoAnyLove\AppData\Local\nvim\plugged\jedi-vim\pythonx\jedi\jedi\api\helpers.py", line 198, in evaluate_goto_definition
    return evaluator.goto_definitions(context, leaf)
  File "C:\Users\NoAnyLove\AppData\Local\nvim\plugged\jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 465, in goto_definitions
    return helpers.evaluate_call_of_leaf(context, name)
  File "C:\Users\NoAnyLove\AppData\Local\nvim\plugged\jedi-vim\pythonx\jedi\jedi\evaluate\helpers.py", line 77, in evaluate_call_of_leaf
    values = context.eval_trailer(values, trailer)
  File "C:\Users\NoAnyLove\AppData\Local\nvim\plugged\jedi-vim\pythonx\jedi\jedi\evaluate\context.py", line 44, in eval_trailer
    return self.evaluator.eval_trailer(self, types, trailer)
  File "C:\Users\NoAnyLove\AppData\Local\nvim\plugged\jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 396, in eval_trailer
    trailer_op, node = trailer.children[:2]
AttributeError: 'Name' object has no attribute 'children'

jedi-vim: No documentation found for that.
```

**Comment by davidhalter** [comment]
@NoAnyLove Jedi version?

**Comment by davidhalter** [comment]
Async/Await support is ready in jedi. Coming with the next release. Please open a new issue if it doesn't work with 0.12.0.
